name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        version: '1.8.0_231'
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64
    - run: |
        mvn install
        docker build ./ -t errorlogger
        docker-compose up        
