name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        version: '9.0.1.3'
    - run: |
        mvn install
        docker build ./ -t errorlogger
        docker-compose up        
